#libraries
library(lsa)
library(vegan)
library(ape)
library(psych)
library(ggplot2)
library(dendextend)
library(circlize)
library(grid)

# feature list humans (leuven) vs feature list gpt

# set working dir to the dir the script is in
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# Load data
leuven_animals = read.csv('../../data/feature_listing/animal_leuven_norms.csv')
leuven_tools = read.csv('../../data/feature_listing/artifacts_leuven_norms.csv')





# Unverified matrix analysis - no matrix completion
gpt_summer_no_mc = read.csv('../../data/feature_listing/gpt_response_unverified_wide_no_matrix_completion.csv')

## Method 2 - mds dissimilarity matrix calculated using cosine distance
<!-- feat_mat_nums<-as.matrix(feat_mat[,2:ncol(feat_mat)])
cor_mat<-1 - cosine(t(feat_mat_nums))  -->
leuven = merge(leuven_animals, leuven_tools, by = 'X', all = TRUE)
leuven[is.na(leuven)] = 0

leuven_cosine_dist = 1-  lsa::cosine(t(data.matrix(leuven[,2:ncol(leuven)])))
leuven_mds <- cmdscale(leuven_cosine_dist,k = 3)
rownames(leuven_cosine_dist) <- leuven$X

unverified_gpt_dsm = 1-  lsa::cosine(t(data.matrix(gpt_summer_no_mc[,2:ncol(gpt_summer_no_mc)])))
unverified_gpt_mds_summer_no_mc <- cmdscale(unverified_gpt_dsm,k = 3)
rownames(unverified_gpt_dsm) <- gpt_summer_no_mc$Concept
rownames(unverified_gpt_mds_summer_no_mc) = rownames(unverified_gpt_dsm)

### proc between leuven and gpt unverified
exp_1_proc <- protest(leuven_mds, unverified_gpt_mds_summer_no_mc)
print('cosine proc')
cat(sqrt(1 - exp_1_proc$ss), exp_1_proc$signif)


 
# Verified matrix analysis - no matrix completion
gpt_summer_no_mc = read.csv('../../data/feature_listing/gpt_response_yes_wide_no_matrix_completion.csv')

## Method 2 - mds dissimilarity matrix calculated using cosine distance
<!-- feat_mat_nums<-as.matrix(feat_mat[,2:ncol(feat_mat)])
cor_mat<-1 - cosine(t(feat_mat_nums))  -->
leuven = merge(leuven_animals, leuven_tools, by = 'X', all = TRUE)
leuven[is.na(leuven)] = 0

leuven_cosine_dist = 1-  lsa::cosine(t(data.matrix(leuven[,2:ncol(leuven)])))
leuven_mds <- cmdscale(leuven_cosine_dist,k = 3)
rownames(leuven_cosine_dist) <- leuven$X

verified_gpt_dsm = 1-  lsa::cosine(t(data.matrix(gpt_summer_no_mc[,2:ncol(gpt_summer_no_mc)])))
verified_gpt_mds_summer_no_mc <- cmdscale(verified_gpt_dsm,k = 3)
rownames(verified_gpt_dsm) <- gpt_summer_no_mc$Concept
rownames(verified_gpt_mds_summer_no_mc) = rownames(verified_gpt_dsm)

### proc between leuven and gpt verified
exp_1_proc <- protest(leuven_mds, verified_gpt_mds_summer_no_mc)
print('cosine proc')
cat(sqrt(1 - exp_1_proc$ss), exp_1_proc$signif)




### proc between gpt unverified and gpt verified
exp_1_proc <- protest(unverified_gpt_mds_summer_no_mc, verified_gpt_mds_summer_no_mc)
print('cosine proc')
cat(sqrt(1 - exp_1_proc$ss), exp_1_proc$signif)

# Make Fan plots

## leuven
hc <- as.dendrogram(hclust(as.dist(leuven_cosine_dist)))
hc <- hc %>%
  color_branches(k = 2) %>%
  color_labels(k = 2)
png("../graphs/leuven.png",  width = 6, height = 6, units = "in", res = 300)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6)
title("Leuven")
dev.off()
        


## GPT(list)
hc <- as.dendrogram(hclust(as.dist(unverified_gpt_dsm)))
hc <- hc %>%
  color_branches(k = 2) %>%
  color_labels(k = 2)
png("../graphs/gpt_list.png",  width = 6, height = 6, units = "in", res = 300)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6)
title("GPT (list)")
dev.off()
pdf(file="../graphs/gpt_list.pdf",width=10, height=10)
par(bg="gray")
plot(as.phylo(hclust(as.dist(unverified_gpt_dsm))), type = "unrooted", main = "Color-concept space", show.tip.label=TRUE)
dev.off()

## GPT(Verified)

hc <- as.dendrogram(hclust(as.dist(verified_gpt_dsm)))
hc <- hc %>%
  color_branches(k = 2) %>%
  color_labels(k = 2)
png("../graphs/gpt_verified.png",  width = 6, height = 6, units = "in", res = 300)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6)
title("GPT (verified)")
dev.off()


