#libraries
library(lsa)
library(vegan)
library(ape)
library(psych)
library(ggplot2)
library(dendextend)
library(circlize)
library(grid)
library(tidyr)


setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# Load data
leuven_animals = read.csv('data/feature_listing/animal_leuven_norms.csv')
leuven_tools = read.csv('data/feature_listing/artifacts_leuven_norms.csv')
gpt_triplet_mds = read.csv('data/triplets/summer_data/gpt_reptile_tool_embedding_df_temp0_cogsci2023.csv')
human_triplet_mds = read.csv('data/triplets/summer_data/human_reptile_tool_embedding_df.csv')

#Flan-xxl

## Flan-xxl feat list
flan_xxl_verified = read.csv('data/feature_listing/flan_xxl_wide.csv')
flan_xxl_dsm = 1-  lsa::cosine(t(data.matrix(flan_xxl_verified[,2:ncol(flan_xxl_verified)])))
flan_xxl_dsm = flan_xxl_dsm[order(flan_xxl_verified$Concept),order(flan_xxl_verified$Concept)]
flan_xxl_mds <- cmdscale(flan_xxl_dsm,k = 3)
rownames(flan_xxl_dsm) <- flan_xxl_verified$Concept
rownames(flan_xxl_mds) = rownames(flan_xxl_dsm)
flan_xxl_mds <- flan_xxl_mds[order(rownames(flan_xxl_mds)),]

## Flan-xxl triplets
flan_xxl_triplet_mds <- read.csv('embeddings_data/flan-t5-xxl.csv')
rownames(flan_xxl_triplet_mds) <- flan_xxl_triplet_mds$concept
flan_xxl_triplet_mds <- flan_xxl_triplet_mds[order(rownames(flan_xxl_triplet_mds)),]
flan_xxl_triplet_mds <- flan_xxl_triplet_mds[, 3:5]
flan_xxl_triplet_dsm = 1-  lsa::cosine(t(data.matrix(flan_xxl_triplet_mds)))

## Flan-xxl pairwise
flan_xxl_pairwise_dsm = read.csv('data/pairwise/flan-xxl/flan_xxl_pairwise_dsm.csv')
flan_xxl_pairwise_dsm = flan_xxl_pairwise_dsm[,2:ncol(flan_xxl_pairwise_dsm)]

#Gpt 002
## Gpt-002 feat list
gpt_summer_no_mc = read.csv('data/feature_listing/gpt_response_yes_wide_no_matrix_completion.csv')
verified_gpt_dsm = 1-  lsa::cosine(t(data.matrix(gpt_summer_no_mc[,2:ncol(gpt_summer_no_mc)])))
verified_gpt_dsm = verified_gpt_dsm[order(gpt_summer_no_mc$Concept),order(gpt_summer_no_mc$Concept)]
verified_gpt_mds_summer_no_mc <- cmdscale(verified_gpt_dsm,k = 3)
rownames(verified_gpt_dsm) <- gpt_summer_no_mc$Concept
rownames(verified_gpt_mds_summer_no_mc) = rownames(verified_gpt_dsm)
verified_gpt_mds_summer_no_mc <- verified_gpt_mds_summer_no_mc[order(rownames(verified_gpt_mds_summer_no_mc)),]

## gpt-002 triplets
rownames(gpt_triplet_mds) <- gpt_triplet_mds$concept
gpt_triplet_mds <- gpt_triplet_mds[order(rownames(gpt_triplet_mds)),]
gpt_triplet_mds <- gpt_triplet_mds[, 3:5]
gpt_triplet_cosine_dist = 1-  lsa::cosine(t(data.matrix(gpt_triplet_mds)))
gpt_triplet_dsm = gpt_triplet_cosine_dist
rownames(gpt_triplet_cosine_dist) <- gpt_triplet_mds$concept

## gpt-002 pairwise
gpt_002_pairwise_dsm = read.csv('data/pairwise/text-davinci-002/mean_response_davinci-002.csv')
gpt_002_pairwise_dsm = gpt_002_pairwise_dsm[1:(nrow(gpt_002_pairwise_dsm)), 2:(ncol(gpt_002_pairwise_dsm)), drop = FALSE]
colnames(gpt_002_pairwise_dsm) <- NULL
gpt_002_pairwise_dsm = (t(as.matrix(gpt_002_pairwise_dsm)) + as.matrix(gpt_002_pairwise_dsm))/2
gpt_002_pairwise_dsm = 7 - gpt_002_pairwise_dsm
gpt_002_pairwise_mds = cmdscale(as.matrix(gpt_002_pairwise_dsm),k = 3)

# gpt-003

## pairwise
gpt_003_pairwise_dsm = read.csv('data/pairwise/text-davinci-003/response_davinci-003_0.7_mean_matrix.csv')
gpt_003_pairwise_dsm = gpt_003_pairwise_dsm[1:(nrow(gpt_003_pairwise_dsm)), 2:(ncol(gpt_003_pairwise_dsm)), drop = FALSE]
colnames(gpt_003_pairwise_dsm) <- NULL
gpt_003_pairwise_dsm = (t(as.matrix(gpt_003_pairwise_dsm)) + as.matrix(gpt_003_pairwise_dsm))/2
gpt_003_pairwise_dsm = 7 - gpt_003_pairwise_dsm
gpt_003_pairwise_mds = cmdscale(as.matrix(gpt_003_pairwise_dsm),k = 3)

#Humans

## Human triplets
rownames(human_triplet_mds) <- human_triplet_mds$concept
human_triplet_mds <- human_triplet_mds[order(rownames(human_triplet_mds)),]
human_triplet_mds <- human_triplet_mds[, 3:5]
human_triplet_cosine_dist = 1-  lsa::cosine(t(data.matrix(human_triplet_mds)))
human_triplet_dsm = human_triplet_cosine_dist
rownames(human_triplet_cosine_dist) <- human_triplet_mds$concept

## Human Feature listing
leuven = merge(leuven_animals, leuven_tools, by = 'X', all = TRUE)
leuven[is.na(leuven)] = 0
leuven_cosine_dist = 1-  lsa::cosine(t(data.matrix(leuven[,2:ncol(leuven)])))
leuven_dsm = leuven_cosine_dist[order(leuven$X),order(leuven$X)]
leuven_mds <- cmdscale(leuven_cosine_dist,k = 3)
rownames(leuven_cosine_dist) <- leuven$X
rownames(leuven_mds) <- leuven$X
leuven_mds <- leuven_mds[order(rownames(leuven_mds)),]

## Human pairwise
human_pairwise_dsm = read.csv('data/pairwise/human/human_pairwise_dsm.csv')
human_pairwise_dsm = human_pairwise_dsm[, 2:ncol(human_pairwise_dsm)]







# Human fan plots

colors <- c("#fc2203", "#580df2", "#34cb8a", "#CB3475", "#CB3475", "#fc2203",
            "#f5650a", "#34cb8a", "#CB3475", "#fc2203", "#fc2203", "#f5650a", "#3368cc",
            "#34cb8a", "#34cb8a", "#3368cc", "#f5650a", "#45a8ba", "#50afa0",
            "#50afa0", "#f5650a", "#34cb8a", "#45a8ba", "#34cb8a", "#CB3475",
            "#45a8ba", "#f4a60b", "#f4a60b", "#f4a60b", "#3368cc")            
## feat list
hc <- as.dendrogram(hclust(as.dist(leuven_cosine_dist), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/humans/leuven.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("Human Feature Listing") -->
dev.off()


## triplets
hc <- as.dendrogram(hclust(as.dist(human_triplet_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/humans/triplet.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("Human Triplets") -->
dev.off()

## pairwise
rownames(human_pairwise_dsm) =rownames(human_triplet_dsm)
hc <- as.dendrogram(hclust(as.dist(human_pairwise_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/humans/pairwise.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("Human Pairwise") -->
dev.off()








# Gpt 002 fan plots
## feature listing
hc <- as.dendrogram(hclust(as.dist(verified_gpt_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/gpt-002/feat.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("GPT(002) Feature Listing") -->
dev.off()

## triplet
hc <- as.dendrogram(hclust(as.dist(gpt_triplet_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/gpt-002/triplet.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("GPT(002) Triplet") -->
dev.off()

## pairwise
hc <- as.dendrogram(hclust(as.dist(gpt_002_pairwise_mds_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/gpt-002/pairwise.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("GPT(002) Pairwise") -->
dev.off()




# Flan-xxl fan plots 
## feature listing
hc <- as.dendrogram(hclust(as.dist(flan_xxl_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/flan-xxl/feat.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("FLAN-XXL Feature Listing") -->
dev.off()


## pairwise
rownames(flan_xxl_pairwise_dsm) = rownames(flan_xxl_dsm)
colnames(flan_xxl_pairwise_dsm) = colnames(flan_xxl_dsm)
hc <- as.dendrogram(hclust(as.dist(flan_xxl_pairwise_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/flan-xxl/pairwise.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("FLAN-XXL Pairwise") -->
dev.off()

## triplet
rownames(flan_xxl_triplet_dsm) = rownames(flan_xxl_dsm)
colnames(flan_xxl_triplet_dsm) = colnames(flan_xxl_dsm)
hc <- as.dendrogram(hclust(as.dist(flan_xxl_triplet_dsm), method = "ward.D2"))
labels_colors(hc) <- as.character(colors)[order.dendrogram(hc)]
pdf("graphs/fan_plots/flan-xxl/triplet.pdf", width = 6, height = 6, onefile = FALSE)
<!-- png("graphs/fan_plots/humans/leuven.png",  width = 6, height = 6, units = "in", res = 300) -->
<!-- <!-- par(mar = c(0, 0, 2, 0)) # increase the bottom margin to move the title up --> -->
par(cex=1.2)
circlize_dendrogram(hc,
                    labels_track_height = 0.3,
                    dend_track_height = 0.6,
                    cex = 10)
options(warn = 0)
<!-- title("FLAN-XXL Triplet") -->
dev.off()


